name: responsive_row
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/welitonsousa/responsive_row
repository: https://github.com/welitonsousa/responsive_row
issue_tracker: https://github.com/welitonsousa/responsive_row/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
